
source 'https://cdn.cocoapods.org/'

use_frameworks!
target 'RKBaseView_Tests' do
  pod 'RKIBaseView', :path => '../'
  #pod 'RKIUtils' #, :git => 'git@gitlab.rokid-inc.com:xr_app_platform/ios/basic/rkutils.git'
  #pod 'RKILogger' #, :git => 'git@gitlab.rokid-inc.com:xr_app_platform/ios/basic/rklogger.git'
end
